<!-- <pre class='xdebug-var-dump' dir='ltr'>
  <b>array</b> <i>(size=2)</i>  0 <font color='#888a85'>=&gt;</font>
    <b>array</b> <i>(size=7)</i>
  'TeaType' <font color='#888a85'>=&gt;</font> <small>boolean</small> <font color='#75507b'>true</font>
  'boba' <font color='#888a85'>=&gt;</font>         <b>array</b> <i>(size=1)</i>0 <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'Green Apple'</font> <i>(length=11)</i>
  'jelly' <font color='#888a85'>=&gt;</font>         <b>array</b> <i>(size=1)</i>          0 <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'Strawberry'</font> <i>(length=10)</i>
  'name' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'Chocolate'</font> <i>(length=9)</i>
  'size' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'REGULAR'</font> <i>(length=7)</i>
  'tapioca' <font color='#888a85'>=&gt;</font> <small>boolean</small> <font color='#75507b'>true</font>
  'type' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'CLASS COM.EXAMPLE.MHO23.FBTWIST.VIEW.TEA'</font> <i>(length=40)</i>  1 <font color='#888a85'>=&gt;</font>
    <b>array</b> <i>(size=7)</i>
  'TeaType' <font color='#888a85'>=&gt;</font> <small>boolean</small> <font color='#75507b'>true</font>
  'boba' <font color='#888a85'>=&gt;</font>         <b>array</b> <i>(size=1)</i>          0 <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'Green Apple'</font> <i>(length=11)</i>
  'jelly' <font color='#888a85'>=&gt;</font>         <b>array</b> <i>(size=1)</i>          0 <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'Strawberry'</font> <i>(length=10)</i>
  'name' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'Chocolate'</font> <i>(length=9)</i>
  'size' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'REGULAR'</font> <i>(length=7)</i>
  'tapioca' <font color='#888a85'>=&gt;</font> <small>boolean</small> <font color='#75507b'>false</font>
  'type' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'CLASS COM.EXAMPLE.MHO23.FBTWIST.VIEW.TEA'</font> <i>(length=40)</i>
</pre> -->

<!-- <pre class='xdebug-var-dump' dir='ltr'><small>string</small> <font color='#cc0000'>'CLASS COM.EXAMPLE.MHO23.FBTWIST.VIEW.TEA'</font> <i>(length=40)</i></pre><pre class='xdebug-var-dump' dir='ltr'><small>string</small> <font color='#cc0000'>'Chocolate'</font> <i>(length=9)</i></pre><pre class='xdebug-var-dump' dir='ltr'><small>boolean</small> <font color='#75507b'>true</font></pre><pre class='xdebug-var-dump' dir='ltr'><b>array</b> <i>(size=1)</i>  0 <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'Green Apple'</font> <i>(length=11)</i></pre><pre class='xdebug-var-dump' dir='ltr'><b>array</b> <i>(size=1)</i>  0 <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'Strawberry'</font> <i>(length=10)</i></pre><pre class='xdebug-var-dump' dir='ltr'><small>string</small> <font color='#cc0000'>'REGULAR'</font> <i>(length=7)</i></pre><pre class='xdebug-var-dump' dir='ltr'><small>boolean</small> <font color='#75507b'>true</font></pre><pre class='xdebug-var-dump' dir='ltr'><small>string</small> <font color='#cc0000'>'CLASS COM.EXAMPLE.MHO23.FBTWIST.VIEW.TEA'</font> <i>(length=40)</i></pre><pre class='xdebug-var-dump' dir='ltr'><small>string</small> <font color='#cc0000'>'Chocolate'</font> <i>(length=9)</i></pre><pre class='xdebug-var-dump' dir='ltr'><small>boolean</small> <font color='#75507b'>true</font></pre><pre class='xdebug-var-dump' dir='ltr'><b>array</b> <i>(size=1)</i>  0 <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'Green Apple'</font> <i>(length=11)</i></pre><pre class='xdebug-var-dump' dir='ltr'><b>array</b> <i>(size=1)</i>  0 <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'Strawberry'</font> <i>(length=10)</i></pre><pre class='xdebug-var-dump' dir='ltr'><small>string</small> <font color='#cc0000'>'REGULAR'</font> <i>(length=7)</i></pre><pre class='xdebug-var-dump' dir='ltr'><small>boolean</small> <font color='#75507b'>false</font></pre> -->
<pre class='xdebug-var-dump' dir='ltr'><b>array</b> <i>(size=3)</i>  0 <font color='#888a85'>=&gt;</font>     <b>array</b> <i>(size=8)</i>
  'TeaType' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'FRUIT'</font> <i>(length=5)</i>
  'boba' <font color='#888a85'>=&gt;</font>         <b>array</b> <i>(size=1)</i>          0 <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'Mango'</font> <i>(length=5)</i>      'jelly' <font color='#888a85'>=&gt;</font>         <b>array</b> <i>(size=1)</i>          0 <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'Strawberry'</font> <i>(length=10)</i>
  'name' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'Taro'</font> <i>(length=4)</i>
  'size' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'LARGE'</font> <i>(length=5)</i>
  'tapioca' <font color='#888a85'>=&gt;</font> <small>boolean</small> <font color='#75507b'>true</font>
  'type' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'TEA'</font> <i>(length=3)</i>
  'userid' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'+17144149534'</font> <i>(length=12)</i>  1 <font color='#888a85'>=&gt;</font>     <b>array</b> <i>(size=8)</i>
  'TeaType' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'FRUIT'</font> <i>(length=5)</i>      'boba' <font color='#888a85'>=&gt;</font>         <b>array</b> <i>(size=1)</i>          0 <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'Mango'</font> <i>(length=5)</i>      
  'jelly' <font color='#888a85'>=&gt;</font>         <b>array</b> <i>(size=1)</i>          0 <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'Strawberry'</font> <i>(length=10)</i>      'name' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'Taro'</font> <i>(length=4)</i>      'size' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'LARGE'</font> <i>(length=5)</i>      'tapioca' <font color='#888a85'>=&gt;</font> <small>boolean</small> <font color='#75507b'>true</font>      'type' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'TEA'</font> <i>(length=3)</i>
  'userid' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'+17144149534'</font> <i>(length=12)</i>  'datetime' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'2018-03-21 12:58:34 pm'</font> <i>(length=22)</i></pre>Order Successfully SubmittedOrder Successfully Submitted<br /><font size='1'><table class='xdebug-error xe-warning' dir='ltr' border='1' cellspacing='0' cellpadding='1'><tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Warning: Illegal string offset 'id' in /vagrant/src/receiveCheckoutPost.php on line <i>61</i></th></tr><tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr><tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr><tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0032</td><td bgcolor='#eeeeec' align='right'>258472</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/vagrant/src/receiveCheckoutPost.php' bgcolor='#eeeeec'>../receiveCheckoutPost.php<b>:</b>0</td></tr></table></font><br /><font size='1'><table class='xdebug-error xe-fatal-error' dir='ltr' border='1' cellspacing='0' cellpadding='1'><tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Only variables can be pass
